const authRoutes = require('./routes/auth');
const taskRoutes = require('./routes/tasks');
const boardRoutes = require('./routes/boards');
const listRoutes = require('./routes/lists');
const folderRoutes = require('./routes/folders');
const docRoutes = require('./routes/docs');
const whiteboardRoutes = require('./routes/whiteboards');
const captchaRoutes = require('./routes/captcha').router;
const fileRoutes = require('./routes/files');
const nodeRoutes = require('./routes/nodes');
const graphRoutes = require('./routes/graphs');
const knowledgeRoutes = require('./routes/knowledge');
const missionRoutes = require('./routes/missions');
const userRoutes = require('./routes/users');
const analyticsRoutes = require('./routes/analytics');
const messageRoutes = require('./routes/messages');
const queryRoutes = require('./routes/queryRoutes');
const callRoutes = require('./routes/callRoutes');

console.log('authRoutes:', typeof authRoutes);
console.log('taskRoutes:', typeof taskRoutes);
console.log('boardRoutes:', typeof boardRoutes);
console.log('listRoutes:', typeof listRoutes);
console.log('folderRoutes:', typeof folderRoutes);
console.log('docRoutes:', typeof docRoutes);
console.log('whiteboardRoutes:', typeof whiteboardRoutes);
console.log('captchaRoutes:', typeof captchaRoutes);
console.log('fileRoutes:', typeof fileRoutes);
console.log('nodeRoutes:', typeof nodeRoutes);
console.log('graphRoutes:', typeof graphRoutes);
console.log('knowledgeRoutes:', typeof knowledgeRoutes);
console.log('missionRoutes:', typeof missionRoutes);
console.log('userRoutes:', typeof userRoutes);
console.log('analyticsRoutes:', typeof analyticsRoutes);
console.log('messageRoutes:', typeof messageRoutes);
console.log('queryRoutes:', typeof queryRoutes);
console.log('callRoutes:', typeof callRoutes);
